---
# tasks file for firefox
- name: Ensure policy directory exists
  ansible.builtin.file:
    path: /etc/firefox/policies
    state: directory

- name: Setup default preferences
  ansible.builtin.copy:
    src: policies.json
    dest: /etc/firefox/policies/policies.json
