---
# tasks file for firefox
- name: Ensure Firefox installed
  become: yes
  package:
    name:
      - firefox

- name: Setup default preferences
  copy:
    src: firefox-prefs.js
    dest: ~/snap/firefox/common/.mozilla/firefox/mozilla.cfg
