---
# tasks file for firefox
- name: Ensure policy directory exists
  file:
    path: /etc/firefox/policies
    state: directory

- name: Setup default preferences
  copy:
    src: policies.json
    dest: /etc/firefox/policies/policies.json
