---
- name: Add clamav user to the tester group (for CI)
  ansible.builtin.user:
    name: clamav
    groups: tester
    append: true

- name: Create clamav runtime directory for PID file (for CI)
  ansible.builtin.file:
    path: /run/clamav
    state: directory
    owner: clamav
    group: clamav
    mode: '0755'

- name: Update virus definitions before first start (for CI)
  ansible.builtin.command:
    cmd: freshclam
  changed_when: false

- name: Start the clamd scanning daemon asynchronously (for CI)
  ansible.builtin.command:
    cmd: clamd --foreground
  async: 45 # Run for up to 45 seconds in the background
  poll: 0   # Fire and forget: don't wait for the task to complete
  changed_when: false

- name: Wait for the clamd socket to become available (for CI)
  ansible.builtin.wait_for:
    path: /run/clamav/clamd.ctl
    # Give it a moment to start, as async is not instantaneous
    delay: 5
    timeout: 15

- name: Start clamonacc with logging (for CI)
  ansible.builtin.command:
    cmd: clamonacc --move={{ clamav_quarantine_dir }} --log=/var/log/clamav/clamonacc.log &
  changed_when: false
