---
- name: Install clamav
  ansible.builtin.package:
    name:
      - clamav
      - clamav-daemon
    state: present

- name: Note ClamAV version and sig versions when running updates
  ansible.builtin.lineinfile:
    path: '{{ update_script }}'
    line: freshclam && clamscan --version

- name: Configure clamav daemon
  ansible.builtin.template:
    src: clamd.conf.j2
    dest: /etc/clamav/clamd.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart clamav-daemon

- name: Update virus definitions before first start
  ansible.builtin.command:
    cmd: freshclam
  changed_when: false

- name: Copy quarantine script
  ansible.builtin.copy:
    src: clamav-quarantine.sh
    dest: /usr/local/bin/clamav-quarantine.sh
    owner: root
    group: root
    mode: '0755'

## Real environment
- name: Ensure clamav-daemon is running and enabled
  ansible.builtin.service:
    name: clamav-daemon
    state: started
    enabled: true
  when: lookup('env', 'CI') != 'true'

## In CI
- name: Add clamav user to the tester group
  ansible.builtin.user:
    name: clamav
    groups: tester
    append: true
  when: lookup('env', 'CI') == 'true'

- name: Create clamav runtime directory for PID file (for CI)
  ansible.builtin.file:
    path: /run/clamav
    state: directory
    owner: clamav
    group: clamav
    mode: '0755'
  when: lookup('env', 'CI') == 'true'

- name: Capture clamd startup output (Temporary Debug Task)
  become: true
  ansible.builtin.command:
    cmd: clamd --foreground
  register: clamd_debug_output
  failed_when: false
  when: lookup('env', 'CI') == 'true'

- name: Display clamd startup output
  ansible.builtin.debug:
    var: clamd_debug_output
  when: lookup('env', 'CI') == 'true'

- name: Wait for the clamd socket to become available (for CI)
  ansible.builtin.wait_for:
    path: /run/clamav/clamd.ctl
    timeout: 10
  when: lookup('env', 'CI') == 'true'

- name: Start clamonacc with logging (for CI)
  become: true
  ansible.builtin.command:
    # Start in the background and tell it to create a log file.
    cmd: clamonacc --log=/var/log/clamav/clamonacc.log &
  when: lookup('env', 'CI') == 'true'
  changed_when: false
