---
- name: Install clamav
  package:
    name:
      - clamav
      - clamav-daemon
    state: present

- name: Note ClamAV version and sig versions when running updates
  become: yes
  become_user: '{{ username }}'
  lineinfile:
    path: '{{ update_script }}'
    line: freshclam && clamscan --version
