---
- name: Install clamav
  ansible.builtin.package:
    name:
      - clamav
      - clamav-daemon
    state: present

- name: Note ClamAV version and sig versions when running updates
  ansible.builtin.lineinfile:
    path: '{{ update_script }}'
    line: freshclam && clamscan --version

- name: Configure clamav daemon
  ansible.builtin.template:
    src: clamd.conf.j2
    dest: /etc/clamav/clamd.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart clamav-daemon

- name: Copy quarantine script
  ansible.builtin.copy:
    src: clamav-quarantine.sh
    dest: /usr/local/bin/clamav-quarantine.sh
    owner: root
    group: root
    mode: '0755'

- name: Add clamav user to the tester group
  ansible.builtin.user:
    name: clamav
    groups: tester
    append: true

- name: Ensure clamav-daemon is running and enabled
  ansible.builtin.service:
    name: clamav-daemon
    state: started
    enabled: true
  when: lookup('env', 'CI') != 'true'

# - name: Start clamav-daemon process manually (in CI environment)
#   ansible.builtin.command:
#     cmd: /etc/init.d/clamav-daemon start
#   when: lookup('env', 'CI') == 'true'
#   changed_when: false # This command doesn't report changes idempotently

- name: Check permissions of the ClamAV log directory (for CI)
  ansible.builtin.command:
    cmd: ls -ld /var/log/clamav/
  when: lookup('env', 'CI') == 'true'
  changed_when: false
  failed_when: false # Don't fail, just show output

- name: Run clamav-daemon in debug mode to see startup errors (for CI)
  ansible.builtin.command:
    cmd: cmd: /usr/sbin/clamd --debug --foreground
  when: lookup('env', 'CI') == 'true'
  changed_when: false