---
- name: Install clamav
  ansible.builtin.package:
    name:
      - clamav
      - clamav-daemon
    state: present

- name: Note ClamAV version and sig versions when running updates
  ansible.builtin.lineinfile:
    path: '{{ update_script }}'
    line: freshclam && clamscan --version
