repos:
  - repo: https://github.com/ansible/ansible-lint
    rev: v26.9.0
    hooks:
      - id: ansible-lint
        language_version: python3
        pass_filenames: true
        always_run: false
        args: [--offline]
        types: [yaml]
        files: ^(workstation\.ya?ml|test\.ya?ml|roles/.*\.(yml|yaml))$
