---
- hosts: localhost
  become_method: sudo
  vars_files:
    - ./.vars.yml
    - ./vars.yml
  roles:
  - role: ./roles/sudo
  - role: ./roles/cleanup
  - role: ./roles/updates

  - role: ./roles/nordvpn
    when: not CI  # no snapd
  
  - role: ./roles/slack
    when: not CI  # no snapd
  
  - role: ./roles/vscode
    when: not CI  # no snapd

  - role: ./roles/xfce
    when: not CI  # needs X11

  - role: ./roles/dev
  - role: ./roles/chrome-browser
  - role: ./roles/git
  - role: ./roles/clamav
