---
- name: Workstation setup
  hosts: localhost
  become: true
  become_method: ansible.builtin.sudo
  vars_files:
    - ./.vars.yml
    - ./vars.yml
  roles:
    - role: networking
    - role: sudo
    - role: cleanup
    - role: updates
    - role: dev
    - role: chrome-browser
    - role: git
    - role: clamav
    - role: slack
      when: not is_gh_actions
    - role: vscode
      when: not is_gh_actions
    - role: xfce
      when: not is_gh_actions
    - role: cups
      when: not is_gh_actions
    - role: clipboard
      when: not is_gh_actions


    # Enable UFW firewall unless running in CI
    - role: ufw
      when: not is_gh_actions

    # must be last, leaves system in a network-disabled state until user activates or disables killswitch
    - role: nordvpn
      when: not is_gh_actions
