---
- hosts: localhost
  become_method: sudo
  vars_files:
    - ./.vars.yml
    - ./vars.yml
  roles:
  - role: ./roles/networking
  - role: ./roles/sudo
  - role: ./roles/cleanup
  - role: ./roles/updates

  - role: ./roles/nordvpn
    when: not is_gh_actions  # no snapd
  
  - role: ./roles/slack
    when: not is_gh_actions  # no snapd
  
  - role: ./roles/vscode
    when: not is_gh_actions  # no snapd

  - role: ./roles/xfce
    when: not is_gh_actions  # needs X11

  - role: ./roles/dev
  - role: ./roles/chrome-browser
  - role: ./roles/git
  - role: ./roles/clamav
  - role: ./roles/cups
    when: not is_gh_actions  # no systemctl in container
  - role: ./roles/clipboard
    when: not is_gh_actions  # no crontab in container

  
