---
- hosts: localhost
  become_method: sudo
  vars_files:
    - ./vars.yml
  roles:
  - role: ./roles/sudo
  - role: ./roles/cleanup
  - role: ./roles/updates
  - role: ./roles/vscode
  - role: ./roles/dev
  - role: ./roles/slack
  - role: ./roles/firefox
  - role: ./roles/chrome-browser
  - role: ./roles/gcloud
  - role: ./roles/expressvpn
  - role: ./roles/pyenv
  - role: ./roles/pipx
  - role: ./roles/pipenv
  - role: ./roles/git
  - role: ./roles/clamav
  - role: ./roles/xfce
    when: in_container is not defined # needs X11
  - role: ./roles/docker-rootless
    when: in_container is not defined # already running in a container
  
  
  
