---
- name: pipx install
  become_user: '{{ username }}'
  shell: |
    . {{ user_profile }}
    pip install --user pipx

- name: pipx update
  become_user: '{{ username }}'
  lineinfile:
    path: '{{ user_update_script }}'
    line: pipx upgrade-all
    