---
- name: pipx install
  become: yes
  become_user: '{{ username }}'
  ansible.builtin.shell: |
    . {{ user_profile }}
    pip install --user pipx

- name: pipx update
  become: yes
  become_user: '{{ username }}'
  ansible.builtin.lineinfile:
    path: '{{ user_update_script }}'
    line: pipx upgrade-all
    