---
- name: pipx install
  shell: |
    . {{ user_profile }}
    pip install --user pipx

- name: pipx update
  become: yes
  lineinfile:
    path: '{{ user_update_script }}'
    line: pipx upgrade-all
    