---
- name: pipx install
  shell: |
    source {{ user_profile }}
    pip install --user pipx

- name: pipx update
  become: yes
  lineinfile:
    path: '{{ update_script }}'
    line: pipx upgrade-all