---
- name: Install xfconf cli tool
  ansible.builtin.package:
    name:
      - xfconf
    state: present

- name: Prepare directory for Thunar shortcut
  ansible.builtin.file:
    path: '{{ user_home }}/.config/Thunar'
    state: directory
    mode: '0755'
    owner: '{{ username }}'

- name: Disable media automounting
  ansible.builtin.command: xfconf-query -c thunar-volman -np /automount-media/enabled -t 'bool' -s 'false'
  changed_when: false

- name: Disable drives automounting
  ansible.builtin.command: xfconf-query -c thunar-volman -np /automount-drives/enabled -t 'bool' -s 'false'
  changed_when: false
