---
# tasks file for chrome-browser
- name: Check that chrome not already installed
  ansible.builtin.stat:
    path: '/usr/bin/google-chrome'
  register: chrome

- name: Run Playbook
  ansible.builtin.import_tasks: tasks.yml
  when: not chrome.stat.exists
