---
# tasks file for chrome-browser
- name: Check that chrome not already installed
  ansible.builtin.stat:
    path: '/usr/bin/google-chrome'
  register: chrome

- name: Run Playbook
  ansible.builtin.import_tasks: tasks.yml
  when: not chrome.stat.exists

- name: Ensures Chrome policy dir exists
  ansible.builtin.file:
    path: /etc/opt/chrome/policies/recommended
    state: directory

- name: Configure Recommended Policies
  ansible.builtin.copy:
    src: recommended.json
    dest: /etc/opt/chrome/policies/recommended/prefs.json

- name: Ensures Chrome policy dir exists
  ansible.builtin.file:
    path: /etc/opt/chrome/policies/managed
    state: directory

- name: Configure Recommended Policies
  ansible.builtin.copy:
    src: managed.json
    dest: /etc/opt/chrome/policies/managed/prefs.json

