---
# tasks file for chrome-browser
- name: Fetch Chrome Browser
  get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /tmp/google-chrome.deb

- name: Install Chrome
  apt:
    deb: /tmp/google-chrome.deb

- name: Ensures Chrome policy dir exists
  file:
    path: /etc/opt/chrome/policies/managed
    state: directory

- name: Configure Chrome Browser
  copy:
    src: chrome-prefs.json
    dest: /etc/opt/chrome/policies/managed/prefs.json



