---
# tasks file for chrome-browser
- name: Fetch Chrome Browser
  ansible.builtin.get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /tmp/google-chrome.deb
    mode: '0644'

- name: Install Chrome
  ansible.builtin.apt:
    deb: /tmp/google-chrome.deb
