---
# tasks file for chrome-browser
- name: Fetch Chrome Browser
  ansible.builtin.get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /tmp/google-chrome.deb

- name: Install Chrome
  ansible.builtin.apt:
    deb: /tmp/google-chrome.deb

- name: Ensures Chrome policy dir exists
  ansible.builtin.file:
    path: /etc/opt/chrome/policies/recommended
    state: directory

- name: Configure Chrome Browser
  ansible.builtin.copy:
    src: chrome-prefs.json
    dest: /etc/opt/chrome/policies/recommended/prefs.json



