- name: Remove unnecessary Bluetooth and mail packages
  ansible.builtin.package:
    name:
      - thunderbird
      - blueman
      - bluez-utils
      - bluez
      - bluetooth
    state: absent
    update_cache: true
    autoremove: true

- name: Stop ModemManager.service (UK Cyber Essentials: unnecessary services)
  ansible.builtin.systemd:
    name: ModemManager
    state: stopped

- name: Disable ModemManager.service (UK Cyber Essentials: unnecessary services)
  ansible.builtin.systemd:
    name: ModemManager.service
    enabled: false
- name: Remove modemmanager package (UK Cyber Essentials: unnecessary software)
  ansible.builtin.package:
    name: modemmanager
    state: absent
    autoremove: true
    update_cache: true
