---
# tasks file for lastpass
- name: Check that expressvpn not already installed
  stat:
    path: '{{ user_home }}/.experessvpn_is_installed'
  register: expressvpn

- include: tasks.yml
  when: not expressvpn.stat.exists

