---
# tasks file for lastpass
- name: Check that expressvpn not already installed
  ansible.builtin.stat:
    path: '{{ user_home }}/.experessvpn_is_installed'
  register: expressvpn

- name: Run Playbook
  ansible.builtin.import_tasks: tasks.yml
  when: not expressvpn.stat.exists

