---
# tasks file for update
- name: Setup root update script
  template:
    src: files/update.j2
    dest: '{{ update_script }}'
    mode: 0755

- name: Add updaters group
  group:
    name: updaters
    state: present

- name: Add current user to updaters group
  user:
    name: '{{ username }}'
    groups: updaters
    append: yes

- name: Allow updaters group to run update script with appropriate privileges
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%updaters'
    line: '%updaters {{ ansible_hostname }}={{ update_script }}'
    validate: visudo -cf %s

- name: Setup user update script
  template:
    src: files/user_update.j2
    dest: '{{ user_update_script }}'
    mode: 0755
    owner: '{{ username }}'
