#!/bin/sh

set -eu

echo "Package updates"

sudo apt-get update
sudo apt-get upgrade

echo "Snap updates"

sudo snap refresh

echo "Firmware updates"

sudo fwupdmgr refresh --force
sudo fwupdmgr get-updates
sudo fwupdmgr update
