#!/bin/sh

set -eu

echo "Package updates"

apt-get update
apt-get upgrade
apt-get autoremove

echo "Snap updates"

snap refresh

echo "Firmware updates"

fwupdmgr refresh --force
fwupdmgr get-updates
fwupdmgr update
#############################
