---
- name: copy media ISO script to unmodifiable location
  ansible.builtin.copy:
    src: files/setup_linux_usb.sh
    dest: /usr/local/bin/setup_linux_usb.sh
    mode: 0755

- name: copy media ansible script to unmodifiable location
  ansible.builtin.copy:
    src: files/setup_ansible_usb.sh
    dest: /usr/local/bin/setup_ansible_usb.sh
    mode: 0755

- name: Add install_users group
  ansible.builtin.group:
    name: install_users
    state: present

- name: Add current user to install_users group
  ansible.builtin.user:
    name: '{{ username }}'
    groups: install_users
    append: yes

- name: Allow cups_users group to start cupsd with appropriate privileges
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%install_users'
    line: '%install_users {{ ansible_hostname }}=/usr/local/bin/setup_ansible_usb.sh, /usr/local/bin/setup_linux_usb.sh'
    validate: visudo -cf %s