---
- name: Restart clamav-daemon (systemd)
  ansible.builtin.service:
    name: clamav-daemon
    state: restarted
  when: lookup('env', 'CI') != 'true'
  listen: "Restart clamav-daemon"

- name: Restart clamav-daemon (CI)
  ansible.builtin.command:
    cmd: /etc/init.d/clamav-daemon restart
  when: lookup('env', 'CI') == 'true'
  listen: "Restart clamav-daemon"
  changed_when: false
