---
# tasks file for nordvpn
- name: Install nordvpn
  ansible.builtin.command: snap install nordvpn
  changed_when: false
  tags: nordvpn

- name: Create nordvpn group
  ansible.builtin.group:
    name: nordvpn
    state: present
  tags: nordvpn

- name: Add user to nordvpn group
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: nordvpn
    append: true
  tags: nordvpn

- name: Connect snap interfaces
  ansible.builtin.command: snap connect nordvpn:{{ item }}
  loop:
    - hardware-observe
    - network-control
    - network-observe
    - firewall-control
    - login-session-observe
    - system-observe
  changed_when: false
  tags: nordvpn

- name: Copy nordvpn configuration script
  ansible.builtin.copy:
    src: configure_nordvpn.sh
    dest: /usr/local/bin/configure_nordvpn.sh
    mode: '0755'
  tags: nordvpn

- name: Run nordvpn configuration script
  ansible.builtin.command: /usr/local/bin/configure_nordvpn.sh
  become: true
  become_user: "{{ ansible_user_id }}"
  changed_when: false
  tags: nordvpn
