---
- name: Download Slack Packagecloud GPG key
  ansible.builtin.get_url:
    url: https://packagecloud.io/slacktechnologies/slack/gpgkey
    dest: /etc/apt/keyrings/slack.asc
    mode: '0644'

- name: Add Slack APT repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/slack.asc] https://packagecloud.io/slacktechnologies/slack/debian jessie main"
    state: present
    filename: slack
    update_cache: true

- name: Install Slack desktop package
  ansible.builtin.apt:
    name: slack-desktop
    state: present
