---
# tasks file for lastpass
- name: "Fetch latest LastPass Linux install"
  get_url:
    url: https://download.cloud.lastpass.com/linux/lplinux.tar.bz2
    dest: ~/Downloads/lplinux.tar.bz2

- name: Create LastPass extract dir
  file:
    path: ~/Downloads/lplinux
    state: directory

- name: Decompress LastPass archive
  unarchive:
    src: ~/Downloads/lplinux.tar.bz2
    dest: ~/Downloads/lplinux

- name: Install LastPass plugins
  command: ./install_lastpass.sh
  args:
    chdir: ~/Downloads/lplinux