---
# tasks file for lastpass
- name: Check that lastpass not already installed
  stat:
    path: '{{ ansible_env.HOME }}/.lastpass_is_installed'
  register: lastpass

- include: tasks.yml
  when: not lastpass.stat.exists