---
# tasks file for lastpass
- name: Check that lastpass not already installed
  ansible.builtin.stat:
    path: '{{ user_home }}/.lastpass_is_installed'
  register: lastpass

- name: Run Playbook
  import_tasks: tasks.yml
  when: not lastpass.stat.exists