---
# tasks file for bin
- name: Create ~/bin directory
  become: yes
  become_user: '{{ username }}'
  file:
    path: '{{ user_home }}/.local/bin'
    state: directory
    mode: '0755'
    owner: '{{ username }}'
 
