---
# tasks file for bin
- name: Create ~/bin directory
  file:
    path: ~/bin
    state: directory
    mode: '0755'
  
- name: Place ~/bin on PATH
  lineinfile:
    dest: ~/.profile
    state: present
    line: 'PATH=$PATH:$HOME/bin'