# Gather service facts for conditional service management
- name: Gather service facts
  ansible.builtin.service_facts:
  when: not is_gh_actions

- name: Stop ModemManager
  ansible.builtin.systemd:
    name: ModemManager
    state: stopped
  when:
    - not is_gh_actions
    - "'ModemManager.service' in ansible_facts.services"

- name: Disable ModemManager
  ansible.builtin.systemd:
    name: ModemManager
    enabled: false
  when:
    - not is_gh_actions
    - "'ModemManager.service' in ansible_facts.services"


- name: Remove modemmanager package
  ansible.builtin.package:
    name: modemmanager
    state: absent
    autoremove: true
    update_cache: true
  when: not is_gh_actions

- name: Stop avahi-daemon
  ansible.builtin.systemd:
    name: avahi-daemon
    state: stopped
  when:
    - not is_gh_actions
    - "'avahi-daemon.service' in ansible_facts.services"

- name: Disable avahi-daemon
  ansible.builtin.systemd:
    name: avahi-daemon
    enabled: false
  when:
    - not is_gh_actions
    - "'avahi-daemon.service' in ansible_facts.services"


- name: Remove avahi-daemon package
  ansible.builtin.package:
    name: avahi-daemon
    state: absent
    autoremove: true
    update_cache: true
  when: not is_gh_actions
