---
- name: Check that pyenv not already installed
  become: yes
  become_user: '{{ username }}'
  stat:
    path: '{{ user_home }}/.pyenv'
  register: pyenv

- name: Fetch installer
  become: yes
  become_user: '{{ username }}'
  get_url:
    url: https://pyenv.run
    dest: /tmp/pyenv.run
  when: not pyenv.stat.exists

- name: Install
  become: yes
  become_user: '{{ username }}'
  shell: cat /tmp/pyenv.run | bash
  when: not pyenv.stat.exists

- name: Setup shims
  become: yes
  become_user: '{{ username }}'
  blockinfile:
    path: '{{ user_profile }}'
    marker: '# {mark} ANSIBLE_PYENV'
    block: |
      export PATH="{{ user_home }}/.pyenv/shims:{{ user_home }}/.pyenv/bin:$PATH"
      eval "$(pyenv init -)"
      eval "$(pyenv virtualenv-init -)"

- name: Install python build system dependencies
  package:
    name:
      - aria2
      - build-essential
      - curl
      - git
      - libbz2-dev
      - libffi-dev
      - liblzma-dev
      - libncurses5-dev
      - libncursesw5-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - llvm
      - make
      - tk-dev
      - wget
      - xz-utils
      - zlib1g-dev

- name: Install python 3.11
  become: yes
  become_user: '{{ username }}'
  shell: |
    . {{ user_profile }}
    pyenv install 3.11
    pyenv global 3.11
    pyenv rehash
