---
# tasks file for dev
- name: Configure file watchers for IDEs, build tooling
  sysctl:
    name: fs.inotify.max_user_watches
    value: '528288'
    state: present

- name: Create SSH dir
  become: yes
  become_user: '{{ username }}'
  file:
    path: "{{ user_home }}/.ssh"
    state: directory
    mode: '0700'

- name: Generate SSH key
  become: yes
  become_user: '{{ username }}'
  openssh_keypair:
    path: "{{ user_home }}/.ssh/id_ssh"
    type: ed25519

- name: Install general cli tools
  package:
    name:
      - jq
      - httpie
      - htop
      - curl
      - file-roller
    state: present
