---
- name: Install general cli tools
  ansible.builtin.package:
    name:
      - jq
      - httpie
      - htop
      - curl
      - file-roller
      - galculator
      - openssh-client
    state: present

- name: Create SSH dir
  become: true
  become_user: '{{ username }}'
  ansible.builtin.file:
    path: "{{ user_home }}/.ssh"
    state: directory
    mode: '0700'

- name: Generate ed25519 SSH key pair if it does not exist
  ansible.builtin.command:
    cmd: "ssh-keygen -t ed25519 -f {{ user_home }}/.ssh/id_ed25519 -N '' -C 'ansible-generated-key'"
    creates: "{{ user_home }}/.ssh/id_ed25519"

- name: Generate SSH key
  become: true
  become_user: '{{ username }}'
  ansible.builtin.command:
    cmd: ssh_keygen -t ed25519 -f ~/.ssh/id_ssh
  changed_when: false

