name: test_install
on:
  push: {}
  schedule:
    - cron: "0 0 * * *"
jobs:
  test_install:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:23.04
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - name: debug info
        run: |
          cat /etc/lsb-release
      - name: update and install pre-reqs
        run: |
          apt-get update
          apt-get -y install git ansible sudo bzip2
      - name: setup user
        run: |
          adduser --disabled-password --quiet --gecos '' tester
          adduser tester sudo
          echo "tester  ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/tester
          su - tester -c id
          su - tester -c "mkdir -p /home/tester/Downloads"
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        run: |
          su - tester -c "cd $GITHUB_WORKSPACE && ansible-playbook -K -e in_container=true workstation.yml"
      
