name: test_install
on:
  push: {}
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * 0"
jobs:
  test_install:
    strategy:
      matrix:
        image:
          - ubuntu:latest
          - ubuntu:rolling
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - name: debug info
        run: |
          cat /etc/lsb-release
      - name: update and install pre-reqs
        run: |
          apt-get update
          apt-get -y install git ansible sudo bzip2 snapd
      - name: setup user
        run: |
          adduser --disabled-password --quiet --gecos '' tester
          su - tester -c id
          su - tester -c "mkdir -p /home/tester/Downloads"
      - name: checkout
        uses: actions/checkout@v4
      - name: setup
        run: |
          cd $GITHUB_WORKSPACE
          cp ${GITHUB_WORKSPACE}/.github/test_vars.yml ${GITHUB_WORKSPACE}/.vars.yml
          ansible-playbook -i inventory workstation.yml 
      - name: check
        shell: bash -l {0}
        run: |
          su - tester -c "alias"
          su - tester -c "git config --list"
          su - tester -c "python --version"
          su - tester -c "! pip install jsonschema # should not work because no venv"
          su - tester -c "clamscan --version"
          su - tester -c ""
          