name: test_install
on:
  - push
jobs:
  test_install:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - name: debug info
        run: |
          cat /etc/lsb-release
      - name: update and install pre-reqs
        run: |
          apt-get update
          apt-get -y install git ansible sudo
      - name: setup user
        run: |
          adduser --disabled-password --quiet --gecos '' tester
          adduser tester sudo
          echo "tester  ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/tester
          su - tester -c id
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        run: |
          su - tester -c "cd $GITHUB_WORKSPACE && ansible-playbook -Kv ci_test.yml"
      
