name: test_install
on:
  - push
jobs:
  test_install:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
      - name: debug info
        run: cat /etc/lsb-release
      - name: update package info
        run: apt-get update
      - name: install pre-reqs
        run: apt-get install -y git ansible
      - name: checkout
        uses: actions/checkout@v3
      
