name: test_install
on:
  - push
jobs:
  test_install:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - name: debug info
        run: |
          cat /etc/lsb-release
          id
          echo ~
      - name: update and install pre-reqs
        run: |
          apt-get update
          apt-get -y install git ansible
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        run: |
          ansible-playbook -v workstation.yml
      
