name: test_install
on:
  push: {}
  schedule:
    - cron: "0 0 * * *"
jobs:
  test_install:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.10
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - name: debug info
        run: |
          cat /etc/lsb-release
      - name: update and install pre-reqs
        run: |
          apt-get update
          apt-get -y install git ansible sudo bzip2
      - name: setup user
        run: |
          adduser --disabled-password --quiet --gecos '' tester
          su - tester -c id
          su - tester -c "mkdir -p /home/tester/Downloads"
          echo ${GITHUB_WORKSPACE}
      - name: check
        run: su - tester -c '${GITHUB_WORKSPACE}/.github/check_install.sh'
        shell: bash
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        run: >
          cd $GITHUB_WORKSPACE && ansible-playbook -e in_container=true workstation.yml --extra-vars 'git_name="Testy McTestface" username=tester git_email="testy@mctestface.com"'
      - name: check
        run: su - tester -c './.github/check_install.sh'
        shell: bash

      
