name: test_install
on:
  - push
jobs:
  test_install:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
      - name: install_pre_reqs
        run: apt-get install git ansible
      - name: checkout
        uses: actions/checkout@v3
      
