name: test_install
on:
  - push
jobs:
  test_install:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
      - name: Run install script
        run: ./setup.sh
        shell: bash
