name: test_install
on:
  push: {}
  schedule:
    - cron: "0 0 * * 0"
jobs:
  test_install:
    strategy:
      matrix:
        image:
          - ubuntu:latest
          - ubuntu:rolling
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - name: debug info
        run: |
          cat /etc/lsb-release
      - name: update and install pre-reqs
        run: |
          apt-get update
          apt-get -y install git ansible sudo bzip2
      - name: setup user
        run: |
          adduser --disabled-password --quiet --gecos '' tester
          su - tester -c id
          su - tester -c "mkdir -p /home/tester/Downloads"
      - name: checkout
        uses: actions/checkout@v3 
      - name: setup
        run: |
          cd $GITHUB_WORKSPACE
          cp ${GITHUB_WORKSPACE}/.github/workflows/test_vars.yml ${GITHUB_WORKSPACE}/.vars.yml
          ansible-playbook -e in_container=true workstation.yml 
      - name: check
        shell: bash -l {0}
        run: |
          su - tester
          alias
          git config --list
          python --version
          clamscan --version
          