---
# tasks file for docker-rootless
- name: Add docker GPG key and repo
  shell: 
    creates: /usr/share/keyrings/docker-archive-keyring.gpg
    cmd: |
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      apt-get update

- name: Install pre-reqs
  package:
    name:
      - uidmap
      - dbus-user-session
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Disable system docker
  shell: systemctl disable --now docker.service docker.socket
  when: in_container is not defined

- name: Find user UID
  command: 'id -u {{ username }}'
  register: the_user_uid
  check_mode: no
  changed_when: false

- name: Determine XDG_RUNTIME_DIR
  set_fact:
    xdg_runtime_dir: '/run/user/{{ the_user_uid.stdout }}'
  changed_when: false

- name: Install docker rootless
  become: yes
  become_user: '{{ username }}'
  environment:
    XDG_RUNTIME_DIR: '{{ xdg_runtime_dir }}'
  shell: |
    dockerd-rootless-setuptool.sh install
    systemctl --user enable docker
  when: in_container is not defined

- name: Set environment variables
  become: yes
  become_user: '{{ username }}'
  blockinfile:
    path: '{{ user_profile }}'
    marker: '# {mark} ANSIBLE_DOCKER'
    block: |
      export DOCKER_HOST=unix:///run/user/${UID}/docker.sock