---
# tasks file for docker-rootless
- name: Add docker GPG key and repo
  become: true
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt-get update

- name: Install pre-reqs
  become: true
  package:
    name:
      - uidmap
      - dbus-user-session
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Disable system docker
  become: true
  shell: systemctl disable --now docker.service docker.socket

- name: Install docker rootless
  shell: |
    dockerd-rootless-setuptool.sh install
    systemctl --user enable docker

- name: Set environment variables
  blockinfile:
    path: ~/.profile
    block: |
      export DOCKER_HOST=unix:///run/user/${UID}/docker.sock